import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    patients: "Patients",
    staff: "Staff",
    inventory: "Inventory",
    pharmacy: "Pharmacy",
    finance: "Finance",
    settings: "Settings",
    login: "Login",
    logout: "Logout",
    registerPatient: "Register Patient",
    staffManagement: "Staff Management",
    history: "History",
    evolution: "Evolution",
    status: "Status",
    active: "Active",
    vacation: "On Vacation",
    off: "Off",
    terminated: "Terminated",
    hospitalName: "Hospital Name",
    patientName: "Patient Name",
    save: "Save",
    cancel: "Cancel",
    search: "Search",
    newCase: "New Case",
    role: "Role",
    admin: "Admin",
    doctor: "Doctor",
    nurse: "Nurse",
    cashier: "Cashier",
    pharmacist: "Pharmacist",
    hr: "HR",
    receptionist: "Receptionist",
    systemAdmin: "System Admin",
    revenue: "Revenue",
    occupancy: "Bed Occupancy",
    leave: "Staff on Leave",
    reorders: "Pharmacy Re-orders",
    tracking: "Patient Live Tracking",
    wait: "Wait Time",
    assignedDr: "Assigned Dr.",
    stage: "Stage",
    inventoryStatus: "Inventory Status",
    schedules: "Staff Schedules",
    amount: "Amount",
    method: "Method",
    timestamp: "Timestamp",
    billing: "Billing & Finance",
    provisioning: "Tenant Provisioning",
    email: "Email Address",
    password: "Password",
    loginPersonnel: "Personnel Authorization",
    accessKey: "Access Key",
    initAccess: "Initialize Access",
    adminPortal: "Administrator Access Portal",
    backToStaff: "Back to Staff Login",
    professionalSolution: "Professional Hospital Management Solution",
    adminPersonnel: "Administrator ID",
    adminKey: "Root Access Key",
    adminLogin: "Login to Root",
    notAuthorizedAdmin: "Access Denied: This portal is reserved for administrators.",
    regTerminal: "Registration Terminal",
    appointmentLoad: "Today's Appointment Load",
    dailyCapacity: "Daily Capacity",
    recentRegistrations: "Recent Registrations",
    newRegistration: "New Registration",
    insuranceVerify: "Insurance Verify",
    labRegistry: "Total Lab Registry",
    avgTriageWait: "Average Triage Wait",
    insuranceVerified: "Insurance Verified",
    emergencyAdmits: "Emergency Admits",
    myPatientQueue: "My Patient Queue",
    dispensingLogs: "Dispensing Logs",
    financialOverview: "Financial Stream Overview",
    staffSchedules: "Staff Schedules",
    criticalInventory: "Critical Inventory",
    viewAll: "View All",
    syncingRecords: "Syncing records...",
    noPatientsRegistered: "No patients registered yet.",
    activeConsultations: "Active Consultations",
    pendingLabResults: "Pending Lab Results",
    surgeriesToday: "Surgeries Today",
    avgConsultTime: "Avg Consult Time",
    pendingPrescriptions: "Pending Prescriptions",
    lowStockAlarms: "Low Stock Alarms",
    narcoticsCount: "Narcotics Count",
    dailyTurnover: "Daily Turnover",
    stockUtilization: "Stock Utilization",
    revenueToday: "Revenue (Today)",
    pendingInvoices: "Pending Invoices",
    successfulPayments: "Successful Payments",
    insuranceClaims: "Insurance Claims",
    years: "Years",
    managingRecords: "Managing {count} Records / Registry Root",
    noRecordsFound: "NO MATCHING RECORDS FOUND",
    demographics: "Demographics",
    contact: "Contact",
    firstName: "First Name",
    lastName: "Last Name",
    dob: "Date of Birth",
    phone: "Phone",
    male: "Male",
    female: "Female",
    other: "Other",
    secureChannelReady: "SECURE_CHANNEL_READY",
    shiftMonFri: "SHIFT_MON_FRI: 08:00 - 16:00",
    setActive: "Set Active",
    onVacation: "On Vacation",
    offDuty: "Off Duty",
    terminateAction: "Terminate",
    fullName: "Full Name",
    designatedRole: "Designated Role",
    halt: "HALT",
    accreditStaff: "ACCREDIT STAFF",
    addStockItem: "ADD STOCK ITEM",
    searchBySku: "Search by SKU",
    stockLevel: "Stock Level",
    minThreshold: "Min Threshold",
    viewTransactionLog: "View Transaction Log",
    newAsset: "New Asset",
    itemName: "Item Name",
    category: "Category",
    unitType: "Unit Type",
    inStock: "In Stock",
    threshold: "Threshold",
    saveAsset: "Save Asset",
    add: "Add",
    remove: "Remove",
    all: "All",
    equipment: "Equipment",
    medicine: "Medicine",
    dailyTotal: "Daily Total",
    recordPayment: "Record Payment",
    fetchingLogs: "Fetching Logs...",
    noTransactions: "No Transactions Recorded",
    patientUid: "Patient UID",
    refNotes: "Ref / Notes",
    approveLog: "Approve Log",
    cash: "Cash",
    card: "Card",
    transfer: "Transfer",
    insurance: "Insurance",
    systemMode: "System Mode",
    cloudSync: "Cloud Sync",
    patientSearchPlaceholder: "Patient search...",
    online: "Online",
    hospitalAbbr: "HSP",
    reason: "Reason",
    vitalsStatus: "Vitals Status",
    action: "Action",
    openFile: "Open File",
    medBotAssistant: "Med-Bot Assistant",
    reviewLabs: "Review Labs",
    staffSchedules: "Staff Schedules",
    criticalInventory: "Critical Inventory",
    autoRestockAll: "Auto-Restock All",
    ACTIVE: "Active",
    ON_VACATION: "On Vacation",
    OFF: "Off Duty",
    TERMINATED: "Terminated",
    DOCTOR: "Doctor",
    NURSE: "Nurse",
    RECEPTIONIST: "Receptionist",
    PHARMACIST: "Pharmacist",
    CASHIER: "Cashier",
    HR: "HR",
    ADMIN: "Admin",
    SYSTEM_ADMIN: "System Admin",
    MALE: "Male",
    FEMALE: "Female",
    OTHER: "Other",
    NA: "N/A",
    noContact: "No Contact",
    NO_PHONE: "No Phone"
  },
  fr: {
    dashboard: "Tableau de Bord",
    patients: "Patients",
    staff: "Personnel",
    inventory: "Inventaire",
    pharmacy: "Pharmacie",
    finance: "Finance",
    settings: "Paramètres",
    login: "Connexion",
    logout: "Déconnexion",
    registerPatient: "Enregistrer Patient",
    staffManagement: "Gestion du Personnel",
    history: "Historique",
    evolution: "Évolution",
    status: "Statut",
    active: "Actif",
    vacation: "En Vacances",
    off: "Absent",
    terminated: "Terminé",
    hospitalName: "Nom de l'Hôpital",
    patientName: "Nom du Patient",
    save: "Enregistrer",
    cancel: "Annuler",
    search: "Rechercher",
    newCase: "Nouveau Cas",
    role: "Rôle",
    admin: "Admin",
    doctor: "Médecin",
    nurse: "Infirmier(ère)",
    cashier: "Caissier",
    pharmacist: "Pharmacien",
    hr: "RH",
    receptionist: "Réceptionniste",
    systemAdmin: "Admin Système",
    revenue: "Revenu",
    occupancy: "Occupation des lits",
    leave: "Congés du personnel",
    reorders: "Réapprovisionnements",
    tracking: "Suivi des Patients",
    wait: "Temps d'attente",
    assignedDr: "Médecin assigné",
    stage: "Étape",
    inventoryStatus: "État de l'inventaire",
    schedules: "Horaires du Personnel",
    amount: "Montant",
    method: "Méthode",
    timestamp: "Horodatage",
    billing: "Facturation & Finance",
    provisioning: "Approvisionnement du Tenant",
    email: "Adresse Email",
    password: "Mot de passe",
    loginPersonnel: "Autorisation du Personnel",
    accessKey: "Clé d'Accès",
    initAccess: "Initialiser l'Accès",
    adminPortal: "Portail d'Accès Administrateur",
    backToStaff: "Retour à l'accès personnel",
    professionalSolution: "Solution Hospitalière de Pointe",
    adminPersonnel: "ID Administrateur",
    adminKey: "Clé d'Accès Racine",
    adminLogin: "Connexion Racine",
    notAuthorizedAdmin: "Accès Refusé : Ce portail est réservé aux administrateurs.",
    regTerminal: "Terminal d'enregistrement",
    appointmentLoad: "Charge de rendez-vous",
    dailyCapacity: "Capacité journalière",
    recentRegistrations: "Enregistrements récents",
    newRegistration: "Nouvel enregistrement",
    insuranceVerify: "Vérifier assurance",
    labRegistry: "Registre labo total",
    avgTriageWait: "Attente triage moyenne",
    insuranceVerified: "Assurance vérifiée",
    emergencyAdmits: "Admissions d'urgence",
    myPatientQueue: "Ma file d'attente",
    dispensingLogs: "Logs de distribution",
    financialOverview: "Aperçu du flux financier",
    staffSchedules: "Horaires du personnel",
    criticalInventory: "Inventaire critique",
    viewAll: "Voir Tout",
    syncingRecords: "Synchronisation...",
    noPatientsRegistered: "Aucun patient enregistré.",
    activeConsultations: "Consultations actives",
    pendingLabResults: "Résultats labo en attente",
    surgeriesToday: "Chirurgies aujourd'hui",
    avgConsultTime: "Temps consult. moyen",
    pendingPrescriptions: "Prescriptions en attente",
    lowStockAlarms: "Alertes stock bas",
    narcoticsCount: "Comptage narcotiques",
    dailyTurnover: "Chiffre d'affaires",
    stockUtilization: "Utilisation du stock",
    revenueToday: "Revenu (Aujourd'hui)",
    pendingInvoices: "Factures en attente",
    successfulPayments: "Paiements réussis",
    insuranceClaims: "Réclamations assurance",
    years: "Ans",
    managingRecords: "Gestion de {count} dossiers / Racine du registre",
    noRecordsFound: "AUCUN DOSSIER CORRESPONDANT",
    demographics: "Démographie",
    contact: "Contact",
    firstName: "Prénom",
    lastName: "Nom de famille",
    dob: "Date de Naissance",
    phone: "Téléphone",
    male: "Masculin",
    female: "Féminin",
    other: "Autre",
    secureChannelReady: "CANAL_SÉCURISÉ_PRÊT",
    shiftMonFri: "HORAIRE_LUN_VEN: 08:00 - 16:00",
    setActive: "Activer",
    onVacation: "En Congé",
    offDuty: "Hors Service",
    terminateAction: "Terminer",
    fullName: "Nom Complet",
    designatedRole: "Rôle Désigné",
    halt: "ARRÊTER",
    accreditStaff: "ACCRÉDITER PERSONNEL",
    addStockItem: "AJOUTER ARTICLE STOCK",
    searchBySku: "Recherche par SKU",
    stockLevel: "Niveau de stock",
    minThreshold: "Seuil minimal",
    viewTransactionLog: "Voir l'historique des transactions",
    newAsset: "Nouvel Actif",
    itemName: "Nom de l'article",
    category: "Catégorie",
    unitType: "Type d'unité",
    inStock: "En stock",
    threshold: "Seuil",
    saveAsset: "Enregistrer l'actif",
    add: "Ajouter",
    remove: "Retirer",
    all: "Tout",
    equipment: "Équipement",
    medicine: "Médicament",
    dailyTotal: "Total Journalier",
    recordPayment: "Enregistrer Paiement",
    fetchingLogs: "Récupération des logs...",
    noTransactions: "Aucune transaction enregistrée",
    patientUid: "UID Patient",
    refNotes: "Réf / Notes",
    approveLog: "Approuver le log",
    cash: "Espèces",
    card: "Carte",
    transfer: "Virement",
    insurance: "Assurance",
    systemMode: "Mode Système",
    cloudSync: "Sync Cloud",
    patientSearchPlaceholder: "Recherche de patient...",
    online: "EN LIGNE",
    hospitalAbbr: "HSP",
    reason: "Raison",
    vitalsStatus: "État des signes vitaux",
    action: "Action",
    openFile: "OUVRIR DOSSIER",
    medBotAssistant: "Assistant Med-Bot",
    reviewLabs: "RÉVISER LABOS",
    staffSchedules: "Horaires du personnel",
    criticalInventory: "Inventaire critique",
    autoRestockAll: "Réapprovisionnement auto",
    ACTIVE: "Actif",
    ON_VACATION: "En Congé",
    OFF: "Hors Service",
    TERMINATED: "Terminé",
    DOCTOR: "Médecin",
    NURSE: "Infirmier(ère)",
    RECEPTIONIST: "Réceptionniste",
    PHARMACIST: "Pharmacien",
    CASHIER: "Caissier",
    HR: "RH",
    ADMIN: "Admin",
    SYSTEM_ADMIN: "Admin Système",
    MALE: "Masculin",
    FEMALE: "Féminin",
    OTHER: "Autre",
    NA: "N/A",
    noContact: "Pas de contact",
    NO_PHONE: "Pas de téléphone"
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem("lang") as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("lang", language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
